### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by strogonoff** [lutaml/lutaml.org#5]
The build is failing since dependency versions are not pinned, so they apparently updated to mutually incompatible versions. Related: https://github.com/aperis-docs/react-static-plugin-aperis-doc-pages/issues/11

**Comment by kwkwan** [comment]
Got it.

**Comment by ronaldtse** [comment]
@kwkwan let's convert this to a Jekyll site for now? Much of the content is wrong...

**Comment by ronaldtse** [comment]
Only this page is relevant. All the other pages are copied from unitsml.org.

https://www.lutaml.org/uml-domain-specific-language/

**Comment by ronaldtse** [comment]
@kwkwan please remove all the other pages and their content. Thanks!

**Comment by ribose-jeffreylau** [comment]
I think this issue has been fixed in https://github.com/lutaml/lutaml.github.io/commit/2753f05401ea91d6452a375b598ab7fb9e77ac04 and can be closed now.
